NSproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('ZNEWS.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL)

ZNEWS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [

    url(r'^main/$', view=NewsCategoryTape.as_view(), name='main_page'),
    url(r'^main/registration/$', view=registration, name='registration'),
    url(r'^main/login/$', view=userlogin, name='login'),
    url(r'^main/logout/$', view=logout_user, name='logout'),
    url(r'^main/cabinet$', view=NSuserCabinet.as_view(), name='cabinet'),
    url(r'^addread/(?P<pk>\d+)$', view=add_read, name='add_read'),
    url(r'^category/(?P<slug>\w+)/$', view=NewsDetail.as_view(), name='category'),

    # url(r'^category/(?P<pk>\d+)/(?P<pk2>\d+)/$', view=NewsContent.as_view(), name='news_content')

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL)

ZNEWS/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from sorl.thumbnail import ImageField, get_thumbnail
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor.fields import RichTextField


class NSuser(AbstractUser):
    USERNAME_FIELD = 'username'
    phone_number = PhoneNumberField(null=True, unique=True)
    photo = models.OneToOneField('Photo', blank=True, null=True)
    news_read = models.IntegerField(null=True, blank=True, default=0)
    news_added = models.IntegerField(null=True, blank=True, default=0)
    news_rejected = models.IntegerField(null=True, blank=True, default=0)
    news_views = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return str(self.username)

    def number(self):
        return str("{} {} {}".format(self.phone_number[0:4],
                                     self.phone_number[4:6],
                                     self.phone_number[6:]))


class NewsPost(models.Model):
    author = models.ForeignKey('NSuser', null=True, blank=True)
    post_header = models.TextField(null=True, blank=True, default="There must be header")
    post_category = models.ForeignKey('Category', null=True)
    post_content = RichTextField(null=True)
    post_photo = models.URLField(null=True, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    post_source = models.URLField(blank=True, null=True, unique=True)
    is_approved = models.BooleanField(default=True)
    what_to_correct = models.TextField(null=True, blank=True)
    read = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.post_header


class Category(models.Model):
    category_name = models.CharField(max_length=60)
    category_icon = models.ImageField(upload_to='media',
                                      blank=True, null=True,
                                      default='media/notebook.png')
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.category_name

    @property
    def slug(self):
        return self.category_name.replace(" ", "_")


class Comment(models.Model):
    user = models.ForeignKey('NSuser', null=True)
    answer_to = models.ForeignKey('Comment', null=True, blank=True)
    post = models.ForeignKey('NewsPost', null=True)
    text = models.TextField(max_length=300, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Photo(models.Model):
    photo_name = models.CharField(max_length=120, blank=True, null=True)
    image = ImageField(upload_to='media', default='')
    link = models.URLField(blank=True, null=True)

    def __str__(self):
        return str(self.photo_name)

    def thumb(self):
        return u'<img src=%s/>' % (get_thumbnail(self.image, "100x100", crop='center', quality=95).url,)
    thumb.short_description = 'Photos'
    thumb.allow_tags = True


class IsReadByUserStatus(models.Model):
    user = models.ForeignKey("NSuser")
    post = models.ForeignKey("NewsPost")
    status = models.BooleanField(default=False)

ZNEWS/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class NSuserForm(ModelForm):
    class Meta:
        model = NSuser
        fields = ('username', 'password', 'email', 'phone_number')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':
                                               "Enter username"}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':
                                                   "Enter password with at least 8 digits"}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder':
                                             "Enter your email"
                                             }),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder':
                                                   "Enter your phone number"
                                                   }),


        }

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if NSuser.objects.filter(phone_number=data):
            raise forms.ValidationError("Phone number already exists")
        return data


class NSuserCabinetForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control square', 'placeholder':
                                                                             "Username"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control square', 'placeholder':
                                                                           "Email"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control square', 'placeholder':
                                                                                 "phone number"}))
    photo = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={}))

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if NSuser.objects.filter(phone_number=data):
            raise forms.ValidationError("Phone number already exists")

    def clean_username(self):
        data = self.cleaned_data['username']
        if NSuser.objects.filter(username=data):
            raise forms.ValidationError("User with this username already exists")

    def clean_email(self):
        data = self.cleaned_data['email']
        if NSuser.objects.filter(email=data):
            raise forms.ValidationError("User with this email already exists")


class LoginForm(forms.Form):

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':
                                                                 "Enter password with at least 8 digits"}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':
                                                             "Enter your username"}))

    def clean_password(self):
        password = self.cleaned_data['password']
        return password

    def clean_username(self):
        username = self.cleaned_data['username']
        return username

ZNEWS/views.py
from django.db import transaction
from django.db.models import F
from django.urls import reverse
from django.views import View
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse

from .models import *
from .forms import *


def add_read(request, pk):
    post = get_object_or_404(NewsPost, id=pk)

    if not IsReadByUserStatus.objects.filter(post=post, user=request.user):
        with transaction.atomic():
            IsReadByUserStatus.objects.create(post=post, user=request.user)
            post.read += 1
            post.save()
            NSuser.objects.filter(id=request.user.id).update(news_read=F("news_read") + 1)
        data = {
            'read': int(post.read)
        }
        return JsonResponse(data)
    else:
        return HttpResponse(status=403)


class NSuserCabinet(View):
    form_class = NSuserCabinetForm
    template_name = 'cabinet.html'

    def get(self, request):
        form = self.form_class({'username': request.user.username,
                                'email': request.user.email,
                                'password': "",
                                'password_repeat': "",
                                'phone_number': request.user.phone_number})
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        errors = {}

        if form.is_valid():
            nsuser = NSuser.objects.get(username=request.user.username)
            nsuser.username = form.cleaned_data['username']
            nsuser.phone_number = form.cleaned_data['phone_number']
            nsuser.email = form.cleaned_data['email']
            nsuser.save()

        else:
            errors = form.errors

        return render(request, self.template_name, {'form': form, 'errors': errors})


class NewsCategoryTape(ListView):
    model = Category
    template_name = 'main_page.html'

    def get_context_data(self, **kwargs):
        context = super(NewsCategoryTape, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class NewsDetail(ListView):
    model = Category
    template_name = 'posts.html'

    def get_context_data(self, **kwargs):

        context = super(NewsDetail, self).get_context_data(**kwargs)
        context['posts'] = NewsPost.objects.filter(
            post_category__category_name=self.kwargs['slug'].replace("_", " ")).order_by('-post_date')
        return context

    def get(self, request, *args, **kwargs):
        context = NewsPost.objects.filter(
            post_category__category_name=self.kwargs['slug'].replace("_", " ")).order_by('-post_date')
        category = get_object_or_404(Category, category_name=self.kwargs['slug'].replace("_", " "))

        if category.is_active is False:
            return redirect('main_page')
        return render(request, 'posts.html', context={'slug': self.kwargs['slug'].replace("_", " "),
                                                      'posts': context})


def registration(request):
    args = {}
    form = NSuserForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            NSuser.objects.create_user(username=request.POST['username'],
                                       password=request.POST['password'],
                                       email=request.POST['email'],
                                       phone_number=request.POST['phone_number'])
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            login(request, user)
            return redirect('main_page')
    else:
        form = NSuserForm()

    args['form'] = form
    return render(request, 'registration.html', {'form': form})


def userlogin(request):
    error = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main_page')
            else:
                error = 'something invalid'
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form, 'error': error})


@login_required(login_url='login')
def logout_user(request):
    logout(request)
    return redirect('main_page')

ZNEWS/templates/cabinet.html
{% extends 'layout.html' %}

{% block content %}


    <div class="container">
    <div class="card sqcard">
        <br>
        <h2>{{ user.username }}</h2>
    <br>
<div class="row">
    <div class="col-sm-4" style="text-align: left">
        <img style="width: 90%; margin-left: 10%" src = {{ user.photo.image.url }} >
    </div>
    <div class="col-sm-8">
            <form action="{% url 'cabinet' %}" method="post">


        {% csrf_token %}

        <div class="container">
            <div class="form-group">
                <label for="username">Username:</label>
                {{ form.username }}
                     {% if errors.username %}

                <div class="alert alert-danger square">
                    <strong>{{ errors.username|escape }}</strong>
                </div>

        {% endif %}


            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                {{ form.email }}
                     {% if errors.email %}

                <div class="alert alert-danger square">
                    <strong>{{ errors.email|escape }}</strong>
                </div>

        {% endif %}
            </div>
            <div class="form-group">
                <label for="phone_number">Phone number:</label>
                {{ form.phone_number }}
                     {% if errors.phone_number %}

                <div class="alert alert-danger square">
                    <strong>{{ errors.phone_number|escape }}</strong>
                </div>

        {% endif %}
            </div>
            <button type="submit" class="float-left btn btn-success">Save</button>
        </div>

    </form>
    </div>
        </div>

    <div class="row" style="text-align: left; margin-left: 5%">
<div class="col-sm-6">
    <br>
        <H2> News read - {{ user.news_read }}</H2>
    <H2> News added - {{ user.news_added }}</H2>
    <H2> News rejected - {{ user.news_rejected }}</H2>
    <H2> Your news viewed {{ user.news_views }} times</H2>
    </div>
    </div>
</div>
    </div>

{% endblock %}

ZNEWS/templates/layout.html
{% load bootstrap4 %}
{% load static %}
{% load thumbnail %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href={% static 'css/ncss.css' %}>

    <title>Title</title>
</head>
<body>
<br>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <!-- Brand/logo -->
    <div class="container">
  <a class="navbar-brand" href={% url 'main_page' %}>News</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
        {% if not user.is_authenticated %}
      <a class="btn btn-success align-right" href={% url 'login' %}>Sign in</a>
    </li>
       <li class="nav-item">
      <a class="btn btn-danger align-right" href={% url 'registration'%}>Sign up</a>
    </li>
      {% elif user.is_authenticated  %}
            {% if user.photo %}
            <li class="nav-item">
            <img style="height: 4%; margin-right: 10px" src={{ user.photo.image.url}}>
            </li>
                {% endif %}
  <li class="nav-item">
      <div class="dropdown">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
    {{ user.username }}
  </button>
  <div class="dropdown-menu square">
    <a class="dropdown-item square" href={% url 'logout' %}>Logout</a>
    <a class="dropdown-item square" href={% url 'cabinet' %}>Cabinet</a>
    <a class="dropdown-item square" href="#">Link 3</a>
  </div>
</div>
    </li>
  {% endif %}
  </ul>
        </div>
</nav>

{% block content %} {% endblock %}
</body>

</html>

ZNEWS/templates/login.html
{% extends 'layout.html' %}

{% block content %}


    <div class="container">
        <br>
        <h2>Login</h2>
     {% if error %}

                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>

        {% endif %}
        <form action="{% url 'login'%}" method="post">
        {% csrf_token %}

            <div class="form-group">
                <label for="username">Username:</label>
{{ form.username }}

            </div>
            <div class="form-group">
                <label for="password">Password:</label>
{{ form.password }}

            </div>
            <button type="submit" value="Login" class="btn btn-success">Submit</button>
        </form>
    </div>

{% endblock %}

ZNEWS/templates/main_page.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
{% load thumbnail %}


    <div class="container">
<div class="row">
{% for category in categories %}
    {% if category.is_active is True %}
    <div class="col-3">

 <a  class="a-opasity-05" href={% url 'category' category.slug %}>
    <img id="myImg" class="card-img-top" src={{ category.category_icon.url }}>
    <div class="card-img-overlay card-text my_card-text ">
        <H2> {{ category.category_name }} </H2>

        <H2><span class="badge badge-black" style="">{{ category.newspost_set.count }} news</span></H2>

    </div>

 </a>


    <br><br>
    </div>
    {% endif %}
{% endfor %}
</div>
    </div>

{% endblock %}

ZNEWS/templates/news_content.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">

    {{ news_content.post_content }}

</div>

{% endblock %}

ZNEWS/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
<div class="row">
    {% for post in posts %}
        {% if post.is_approved is True %}
        <div class="col-sm-4">
    <div class="card sqcard " >
        {% if user.is_authenticated %}

            <a style="text-decoration: none; color: black;" class="decoration_none ajaxlink"  data-toggle="modal" data-target="#{{ post.id }}" href={% url 'add_read' post.id %}>
        {% else%}
                        <a style="text-decoration: none; color: black;" class="decoration_none"  data-toggle="modal" data-target="#{{ post.id }}" href={% url 'add_read' post.id %}>
        {% endif%}
        <img id="myImg" class="card-img-top" src={{ post.post_photo }}>

        <div class="card-body" style="height: 150px;">
            {{ post.post_header }}
            </div>
        <div class="card-footer" style="background: white;">
                <span class="badge square read-counter"> viewed {{ post.read }} times </span>
                <span class="badge square">{{ post.post_date|date:"N j l H i " }}</span>

        </div>
            </a>

    </div>
        <br><br><br>
        </div>

    {% endif %}

<div class="modal fade" id={{ post.id }}>
  <div class="modal-dialog modal-lg ">
    <div class="modal-content">
      <div class="modal-body">
        {{ post.post_content|safe }}
      </div>
    </div>
  </div>
</div>
    {% endfor %}
</div>
    </div>
     <script>

        $(function () {

            // We can attach the `fileselect` event to all file inputs on the page
            $(document).on('click', '.ajaxlink', function (e) {
                e.preventDefault();
                var post = $(this);
                var spancounter = post.find('.read-counter');

                 $.ajax({ url: post.attr('href')}).done(function (data) {
                        var counter = data.read;
                        spancounter.text('viewed ' + counter + ' times');
                             console.log('done')
                         });

                console.log('read')
            });
        });

    </script>
{% endblock %}

ZNEWS/templates/registration.html
{% extends 'layout.html' %}

{% block content %}


    <form action="{% url 'registration' %}" method="post">


        {% csrf_token %}

        <div class="container">
            <h2>Registration</h2>
            <br>
            <div class="form-group">
                <label for="username">Username:</label>
                {{ form.username }}

                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                {{ form.email }}
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>

                    {% endfor %}

                {% endif %}
            </div>


            <div class="form-group">
                <label for="password">Password:</label>
                {{ form.password }}
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}

                {% endif %}
            </div>
            <div class="form-group">
                <label for="phone_number">Phone number:</label>
                {{ form.phone_number }}
                {% if form.phone_number.errors %}
                    {% for error in form.phone_number.errors %}
                        <div class="alert alert-danger">

                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>

{% endblock %}